version: "3"
services:
  backend:
    image: deciploy/backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=deciployDB
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deciployDB
    volumes:
      - ./data:/var/lib/postgresql/data
