spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true

security:
  jwt:
    secret: { JWT_SECRET }
    expire: { JWT_EXPIRE }
  super-user:
    email: superuser@deciploy.com
    password: dev@1234

springdoc:
  api-docs:
    path: /api-docs


