spring:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/deciployDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true

security:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expire: 360000



