spring:
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true

security:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expire: 3600000
springdoc:
  api-docs:
    path: /api-docs


