name: Deploy spring app to AWS Elastic Beanstalk

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: build with Maven
        env:
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/backend-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/dev'
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.AWS_APPLICATION_NAME }}
          environment_name: ${{ vars.AWS_ENVIRONMENT_NAME }}
          version_label: ${{ github.SHA }}
          region: us-west-2
          deployment_package: backend-0.0.1-SNAPSHOT.jar
